= Aufgabe 1: Vagrant

Aufgabe ist es 4 Maschinen mittels eines Vagrantfiles zu beschreiben und zu
starten. Diese Maschinen dienen als Grundlage für die weiteren Aufgaben.

== Spezifikation

.Inventory
Legt ein Inventory an. Dies sollte für alle 4 Hosts einen Eintrag enthalten.
bccontroller sollte eine local connection verwenden.

Für die dockerhosts setzt bitte die IP Adresse (ansible_ssh_host) und spezifiziert
den privaten Schlüssel.

Erzeugt dann eine Gruppe "dockerhosts", welche dh1 bis dh3 enthält.


== Hinweise

Vagrant legt den Privaten Schlüssel unter +.vagrant/machines/<machine>/virtualbox/private_key+
ab.

Bevor ihr anfangt zu provisionieren führt einmal das link:https://gist.github.com/rattermeyer/06941f38f11040747acd50d8eca8e511[fix-mirror.yml]
Playbook aus.

Dies sorgt auf den Dockerhosts dafür, dass ihr einen "optimalen" mirror verwendet und nicht den langsamen Mirror in den USA.

.ansible.cfg
Für die aktuellen Aufgaben ist es gut eine eigene ansible.cfg anzulegen.
Ihr könnt dort etwa `host_key_checking` für die Entwicklung ausschalten.


== Fragen

== Lösung

Eine mögliche Lösung findet ihr unter dem Tag "solution_2".
