= Aufgabe 2: Ansible

Aufgabe ist es auf den Dockerhosts mittels eines Playbooks Docker zu installieren.

== Spezifikation

.Inventory
Legt ein Inventory an. Dies sollte für alle 4 Hosts einen Eintrag enthalten.
bccontroller sollte eine local connection verwenden.

Für die dockerhosts setzt bitte die IP Adresse (ansible_ssh_host) und spezifiziert
den privaten Schlüssel.

Erzeugt dann eine Gruppe "dockerhosts", welche `dh1` bis `dh3` enthält.

.Playbook
Erstellt ein Playbook `docker.yml`. Ihr solltet mittels der Role `rattermeyer.docker` docker installieren.
Installiert diese Version durch Erstellung einer Datei `requirements.yml` und tragt dort die Abhängigkeit ein und installiert sie mittels
`ansible-galaxy`.
In der aktuellen Ansible Version (2.1.2) gibt es ein Problem mit dem Vergleich.
Erzwingt zur Umgehung des Problems die Installation von docker_py in der Version "1.7.0".

== Hinweise
Lest euch die Anleitung zur link:https://galaxy.ansible.com/rattermeyer/docker/[Docker Rolle] durch.
Dort sind Hinweise gegeben, welche Variablen existieren.
Schaut euch die link:http://docs.ansible.com/ansible/playbooks_roles.html[Roles]
Dokumentation an, um zu verstehen, wie man Variablen spezifizieren kann.

.ansible.cfg
Für die aktuellen Aufgaben ist es gut eine eigene ansible.cfg anzulegen.
Ihr könnt dort etwa `host_key_checking` für die Entwicklung ausschalten.


== Fragen
Gibt es alternative Möglichkeiten die Variablen zu spezifizieren?
Wenn ja, wann sollte man welche Möglichkeit verwenden?

== Lösung

Eine mögliche Lösung findet ihr unter dem Tag "solution_2".
