= Aufgabe 3: Dockerfiles + Provisioning

In dieser Aufgabe geht es hauptsächlich um die Erarbeitung von Dockergrundlagen.
Gleichzeitig vertiefen wir die Ansible Kenntnisse, indem wir Ansible benutzen, um
Docker Container zu deployen.

== Spezifikation

Erweitert das Ansible `inventory` um zwei Gruppen:

* database
* dockerregistry

Die Gruppe "database" soll nur `dh1` und die Gruppe "dockerregistry" nur `dh2` umfassen.

.Dockerregistry
Erstellt dann ein playbook `dockerregistry`, welches die offizielle link:https://hub.docker.com/_/registry/[dockerregistry] deployed.
Verwendet hierfür die Version `2.5.1`.

Probiert ein einfaches Dockerfile zu pullen, taggen und in die Registry zu pushen.
Probiert dies auf dh1 und dh2 aus. Wo funktioniert es, wo nicht?

Passt die Konfiguration des Docker Daemeons im Docker Playbook an.
Definiert dh2 als insecure registry.

.MySql
Jetzt deployed eine MySql Datenbank. Verwendet dazu das link:https://hub.docker.com/_/mysql/[offizielle Image], Version 5.7

* Erreichbar von außen über Port 3306
* Datebankdateien sollen bei Neustart des Containers nicht verloren gleichen


== Hinweise

== Fragen

== Lösung

Eine mögliche Lösung findet ihr unter dem Branch "solution_3".
