= Aufgabe 3: Dockerfiles + Provisioning

In dieser Aufgabe soll zum einen ein vodefiniertes MYSQL Image deployed werden.
Zum anderen soll ein Dockerfile für die Spring Petclinic erstellt, getestet und
dann ebenefalls deployed werden, welches die MySQL benutzt.

Damit wir das Docker Image von allen Hosts später zugreifen können,
deployen wir noch eine Docker Registry und pushen das Image dort hinein.

== Spezifikation

Erstellt ein Playbook `registry.yml`, welches die offizielle registry (version 2) deployed.
Dies machen wir auf dh2.

Passt euer Playbook an, welches docker verteilt. Die Docker Options müssen so angepasst werden, dass
dh2 als insecure registry zugelassen ist (auf allen hosts).
Versucht jetzt auf dh1 ein kleines Image zu pullen (etwa alpine), so zu taggen, dass ihr es in eure eigene registry pushen könnt.
Und pusht es dann.

Erstellt ein Playbook `database.yml`, welches MySQL in der Version 5.7.15 installiert.
Nutzt dazu das offizielle MYSQL Image.

Die MySQL Datenbank sollte auf dem dh1 deployed werden.
Die Daten sollten sich auf dem Host befinden, so dass sie auch nach dem
Deployment einer neuen MySQL Version erhalten bleiben.

Die spring petclinic findet ihr unter `https://github.com/spring-projects/spring-petclinic`.
Erstellt eine Rolle `petclinic`. Legt das Dockerfile im Unververzeichnis `files` ab.
Nutzt als Base Image das offizielle `maven:3.3.9-jdk-8` Image.

Automatisiert bauen und deployment des Petclinic Containers mittels ansible und deployed den Container ebenfalls auf dh1.

== Hinweise
Überlegt, wie ihr den MySQL Container aus dem Petclinic container "ansprechen" könnt.
Es gibt mehrere Möglichkeiten, die teilweise aber auch Einschränkungen haben.
Tauscht euch über die Lösungsmöglichkeiten aus.

== Fragen
Könnt ihr den Petclinic Container auch auf `dh2` ausrollen? Probiert es aus.
Diskutiert, welche Optionen es gibt dieses Problem zu lösen.

== Lösung

Eine mögliche Lösung findet ihr unter dem Branch "solution_03".
