- hosts: database
  tasks:
  - name: "ensure mysql data directory exists"
    file:
      path: "/srv/mysql/data"
      state: directory
  - name: "install mysql"
    docker_container:
      name: "mysql"
      image: "mysql:5.7.15"
      ports:
        - "3306:3306"
      volumes:
        - "/srv/mysql/data:/var/lib/mysql"
      env:
        MYSQL_ROOT_PASSWORD: petclinic
        MYSQL_DATABASE: petclinic
