- hosts: dockerhosts
  pre_tasks:
    - name: "install aufs"
      apt: 
        name: aufs-tools
  roles:
    - role: rattermeyer.docker
      docker_group_members: vagrant
      pip_version_docker_py: "1.7.0"
